import type { Challenge } from '@/types/Challenge';
import { v4 as uuidv4 } from 'uuid';

import {
  DEFAULT_NORMAL_RULES,
  DEFAULT_SCORE_RULES,
  DEFAULT_SPEED_RULES,
} from './defaultRules';

export const CHALLENGE_DATA: Challenge[] = [
  {
    id: '1',
    title: 'Desafio1',
    categories: ['Arte'],
    type: 'speed',
    image: '/imgs/challenge.svg',
    challenges: ['Desafio'],
    rules: DEFAULT_SPEED_RULES,
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Rerum libero aliquam deserunt vel eaque dolorem perspiciatis laudantium ipsam dolor fugit non eligendi totam ea illum recusandae, nam iusto sit consequatur?',
    createdBy: 'deide_costa',
    status: 'waiting',
  },
  {
    id: '2',
    title: 'Desafio2',
    categories: ['Música'],
    type: 'speed',
    image: '/imgs/challenge.svg',
    challenges: ['Desafio'],
    rules: DEFAULT_SPEED_RULES,
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Rerum libero aliquam deserunt vel eaque dolorem perspiciatis laudantium ipsam dolor fugit non eligendi totam ea illum recusandae, nam iusto sit consequatur?',
    createdBy: 'user1231412',
    status: 'waiting',
  },
  {
    id: '3',
    title: 'Desafio3',
    categories: ['Comunicação'],
    type: 'normal',
    image: '/imgs/challenge.svg',
    challenges: ['Desafio'],
    rules: DEFAULT_NORMAL_RULES,
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Rerum libero aliquam deserunt vel eaque dolorem perspiciatis laudantium ipsam dolor fugit non eligendi totam ea illum recusandae, nam iusto sit consequatur?',
    createdBy: 'user1231412',
    status: 'waiting',
  },
  {
    id: '4',
    title: 'Desafio4',
    categories: ['Dança'],
    type: 'normal',
    image: '/imgs/challenge.svg',
    challenges: ['Desafio'],
    rules: DEFAULT_NORMAL_RULES,
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Rerum libero aliquam deserunt vel eaque dolorem perspiciatis laudantium ipsam dolor fugit non eligendi totam ea illum recusandae, nam iusto sit consequatur?',
    createdBy: 'user1231412',
    status: 'waiting',
  },
  {
    id: '5',
    title: 'Desafio5',
    categories: ['Video'],
    type: 'score',
    image: '/imgs/challenge.svg',
    challenges: ['Desafio Score 1', 'Desafio Score 2'],
    rules: DEFAULT_SCORE_RULES,
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Rerum libero aliquam deserunt vel eaque dolorem perspiciatis laudantium ipsam dolor fugit non eligendi totam ea illum recusandae, nam iusto sit consequatur?',
    createdBy: 'user1231412',
    status: 'waiting',
  },
  {
    id: '6',
    title: 'Desafio6',
    categories: ['Design'],
    type: 'score',
    image: '/imgs/challenge.svg',
    challenges: ['Desafio Score 1', 'Desafio Score 2'],
    rules: DEFAULT_SCORE_RULES,
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Rerum libero aliquam deserunt vel eaque dolorem perspiciatis laudantium ipsam dolor fugit non eligendi totam ea illum recusandae, nam iusto sit consequatur?',
    createdBy: 'user1231412',
    status: 'waiting',
  },
  {
    id: '7',
    title: 'Desafio7',
    categories: ['Video'],
    type: 'score',
    image: '/imgs/challenge.svg',
    challenges: ['Desafio Score 1', 'Desafio Score 2'],
    rules: DEFAULT_SCORE_RULES,
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Rerum libero aliquam deserunt vel eaque dolorem perspiciatis laudantium ipsam dolor fugit non eligendi totam ea illum recusandae, nam iusto sit consequatur?',
    createdBy: 'user1231412',
    status: 'waiting',
  },
];
